spring:
  datasource:
    dmmds:
      username: root
      password: root
      url: jdbc:h2:mem:dmmds
      driver-class-name: org.h2.Driver
    dbcmd:
      #primary: true
      username: root
      password: root
      url: jdbc:h2:mem:dbcmd
      driver-class-name: org.h2.Driver
